version: "3.8"

services:
  server:
    build: ./server
    ports:
      - "8080:8080"
    environment:
      - PORT=8080

  client:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - server